### PR TITLE
Add an image loader component which has error handling

### PR DESCRIPTION
**Pull request by yudistrange**
To address #26 and refactor image handling:

- Extracted the ImagePair to its own component
- Extracted an Image container with error handling on image load failure
- Started using the vuex state management for images

### CODE REVIEW

**Comment by loleg** [comment]
Thanks for the proposal. Instead of a fallback image, I would like to use the existing error message (prompt) which appears in case of a network outage - see https://github.com/Streetwise/streetwise-app/blob/master/src/components/ImageVote.vue#L129

And I think that the image pair is really the only place we need to do something.

**Comment by loleg** [comment]
Also, please write up an issue with the problem/proposal before starting a PR linked to it.

**Comment by loleg** [comment]
@yudistrange the code snippet we discussed earlier:

https://github.com/Streetwise/streetwise-app/blob/master/src/components/ImageVote.vue#L121

**Comment by loleg** [comment]
Added #26 and link in the description of this PR. As per my [earlier comment](#issuecomment-629161767), please make sure this happens first next time :)

**Comment by loleg** [comment]
Speaking of error handling, could you please remove the `INFO` level logs from "/api/image/random" which are both taking up a lot of our log bandwidth, and leaking potentially sensitive information.

**Comment by loleg** [comment]
What about logging these errors with the backend?

**Comment by yudistrange** [comment]
Closing this PR as it snowballed into a lot of things. Going to carve it out into multiple PRs.

**Comment by yudistrange** [comment]
Closed in favour of this PR: https://github.com/Streetwise/streetwise-app/pull/40

**Pull request closed without merging**
