### PR TITLE
Increase the column length for agent-string in sessions table

### PR DESCRIPTION
**Pull request by yudistrange**
Addresses #27

### CODE REVIEW

**Comment by yudistrange** [comment]
@loleg unable to generate migration file. Should have generated via `flask db migrate` but it shows not changes.

**Comment by loleg** [comment]
Column size is not something Alembic auto-detects by default. I've added a parameter which solved the issue you were having @yudistrange

**Comment by yudistrange** [comment]
Sweet. Thanks!

**Comment by yudistrange** [comment]
CI tests seem to be failing because sqlite doesn't support alter column command.

**Comment by yudistrange** [comment]
@loleg shall I merge in this as well?

**Pull request merged**
